spring:
  profiles:
    active: "dev"
  output:
    ansi:
    enabled: ALWAYS


---

spring:
  profiles: dev

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/home/gael/PROJECTS/learnphrasebot/data/botdb
    username:
    password:

    hikari:
      connection-timeout: 6000
      auto-commit: true
      username:
      password:
  liquibase:
    enabled: true
    url: jdbc:h2:file:/home/gael/PROJECTS/learnphrasebot/data/botdb


logging:
  config: classpath:${logback:logback_debug.xml}


---

spring:
  profiles: docker

  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    driver-class-name: org.h2.Driver

    username:
    password:

    hikari:
      connection-timeout: 6000
      auto-commit: true
      username:
      password:
  liquibase:
    enabled: true

proxy:
  enabled: false


logging:
  config: classpath:${logback:logback-spring.xml}